# Generated by Django 5.2.8 on 2026-08-20 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_alter_order_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_status',
            field=models.CharField(choices=[('waiting', 'Ожидает оплаты'), ('checking', 'Проверка оплаты'), ('paid', 'Оплачен'), ('refunded', 'Возврат')], default='waiting', max_length=20),
        ),
    ]
